const products = [
  {
    id: "daiso-card-storage-2-pack",
    name: "卡牌收納盒/2入",
    brand: "DAISO",
    model: "9.9 x 3.6 x 7.7 cm",
    widthCm: 9.9,
    depthCm: 3.6,
    heightCm: 7.7,
    priceTwd: 49,
    channel: "DAISO",
    purchaseUrl: "https://shop.daiso.com.tw/pages/daiso01-1",
    imageUrl: "",
    hasLid: false,
    isTransparent: true,
    isStackable: false,
    material: "未標示",
    color: "未標示",
    category: "居家收納",
    style: "小型透明/日常收納",
    note: "官方列表標示日本製；材質與圖片待商品詳頁確認；外徑依尺寸原文順序拆分",
    updatedAt: "2026-07-15",
  },
  {
    id: "daiso-b6-small-storage-box",
    name: "B6小物收納盒",
    brand: "DAISO",
    model: "未標示",
    widthCm: null,
    depthCm: null,
    heightCm: null,
    priceTwd: 49,
    channel: "DAISO",
    purchaseUrl: "https://shop.daiso.com.tw/pages/daiso01-1",
    imageUrl: "",
    hasLid: false,
    isTransparent: false,
    isStackable: false,
    material: "未標示",
    color: "未標示",
    category: "居家收納",
    style: "小型日常收納",
    note: "官方列表顯示售完；尺寸與材質待商品詳頁確認",
    updatedAt: "2026-07-15",
  },
  {
    id: "daiso-divider-storage-box",
    name: "分隔收納盒",
    brand: "DAISO",
    model: "17.5 x 28 x 4.5 cm",
    widthCm: 17.5,
    depthCm: 28,
    heightCm: 4.5,
    priceTwd: 99,
    channel: "DAISO",
    purchaseUrl: "https://shop.daiso.com.tw/pages/daiso01-1",
    imageUrl: "",
    hasLid: false,
    isTransparent: false,
    isStackable: false,
    material: "未標示",
    color: "未標示",
    category: "居家收納",
    style: "低高度分隔收納",
    note: "官方列表顯示售完；材質與圖片待商品詳頁確認；外徑依尺寸原文順序拆分",
    updatedAt: "2026-07-15",
  },
  {
    id: "daiso-stackable-divider-storage-box",
    name: "DAISO可堆疊分隔收納盒",
    brand: "DAISO",
    model: "10.7 x 15.2 x 8.3 cm",
    widthCm: 10.7,
    depthCm: 15.2,
    heightCm: 8.3,
    priceTwd: 49,
    channel: "DAISO",
    purchaseUrl: "https://shop.daiso.com.tw/pages/daiso01-1",
    imageUrl: "",
    hasLid: false,
    isTransparent: false,
    isStackable: true,
    material: "未標示",
    color: "未標示",
    category: "居家收納",
    style: "可堆疊/分隔",
    note: "官方列表標示日本製；材質與圖片待商品詳頁確認；外徑依尺寸原文順序拆分",
    updatedAt: "2026-07-15",
  },
  {
    id: "daiso-clear-lidded-storage-box",
    name: "透明附蓋收納盒",
    brand: "DAISO",
    model: "28 x 19 x 14.5 cm",
    widthCm: 28,
    depthCm: 19,
    heightCm: 14.5,
    priceTwd: 99,
    channel: "DAISO",
    purchaseUrl: "https://shop.daiso.com.tw/pages/daiso01-1",
    imageUrl: "",
    hasLid: true,
    isTransparent: true,
    isStackable: false,
    material: "未標示",
    color: "透明",
    category: "居家收納",
    style: "透明/附蓋",
    note: "官方列表顯示TOP10與售完；材質與圖片待商品詳頁確認；外徑依尺寸原文順序拆分",
    updatedAt: "2026-07-15",
  },
  {
    id: "daiso-stackable-storage-box-small",
    name: "DAISO可堆疊收納盒",
    brand: "DAISO",
    model: "10.7 x 15.2 x 8.3 cm",
    widthCm: 10.7,
    depthCm: 15.2,
    heightCm: 8.3,
    priceTwd: 49,
    channel: "DAISO",
    purchaseUrl: "https://shop.daiso.com.tw/pages/daiso01-1",
    imageUrl: "",
    hasLid: false,
    isTransparent: false,
    isStackable: true,
    material: "未標示",
    color: "未標示",
    category: "居家收納",
    style: "可堆疊",
    note: "官方列表標示日本製；材質與圖片待商品詳頁確認；外徑依尺寸原文順序拆分",
    updatedAt: "2026-07-15",
  },
  {
    id: "daiso-stackable-storage-box-medium",
    name: "DAISO可堆疊收納盒",
    brand: "DAISO",
    model: "15.2 x 21.5 x 8.3 cm",
    widthCm: 15.2,
    depthCm: 21.5,
    heightCm: 8.3,
    priceTwd: 49,
    channel: "DAISO",
    purchaseUrl: "https://shop.daiso.com.tw/pages/daiso01-1",
    imageUrl: "",
    hasLid: false,
    isTransparent: false,
    isStackable: true,
    material: "未標示",
    color: "未標示",
    category: "居家收納",
    style: "可堆疊",
    note: "官方列表標示日本製；材質與圖片待商品詳頁確認；外徑依尺寸原文順序拆分",
    updatedAt: "2026-07-15",
  },
  {
    id: "daiso-stackable-lidded-storage-box",
    name: "DAISO可堆疊附蓋收納盒",
    brand: "DAISO",
    model: "21.5 x 15.5 x 9.9 cm",
    widthCm: 21.5,
    depthCm: 15.5,
    heightCm: 9.9,
    priceTwd: 69,
    channel: "DAISO",
    purchaseUrl: "https://shop.daiso.com.tw/pages/daiso01-1",
    imageUrl: "",
    hasLid: true,
    isTransparent: false,
    isStackable: true,
    material: "未標示",
    color: "未標示",
    category: "居家收納",
    style: "可堆疊/附蓋",
    note: "官方列表標示日本製；材質與圖片待商品詳頁確認；外徑依尺寸原文順序拆分",
    updatedAt: "2026-07-15",
  },
  {
    id: "daiso-folding-handle-basket-medium",
    name: "折疊式提把收納籃",
    brand: "DAISO",
    model: "38 x 25 x 20.4 cm",
    widthCm: 38,
    depthCm: 25,
    heightCm: 20.4,
    priceTwd: 99,
    channel: "DAISO",
    purchaseUrl: "https://shop.daiso.com.tw/pages/daiso01-14",
    imageUrl: "",
    hasLid: false,
    isTransparent: false,
    isStackable: false,
    material: "未標示",
    color: "未標示",
    category: "折疊收納盒",
    style: "折疊/提把",
    note: "官方列表顯示售完；材質與圖片待商品詳頁確認；外徑依尺寸原文順序拆分",
    updatedAt: "2026-07-15",
  },
  {
    id: "daiso-folding-handle-basket-large",
    name: "折疊式提把收納籃",
    brand: "DAISO",
    model: "47.8 x 34.9 x 24.5 cm",
    widthCm: 47.8,
    depthCm: 34.9,
    heightCm: 24.5,
    priceTwd: 139,
    channel: "DAISO",
    purchaseUrl: "https://shop.daiso.com.tw/pages/daiso01-14",
    imageUrl: "",
    hasLid: false,
    isTransparent: false,
    isStackable: false,
    material: "未標示",
    color: "未標示",
    category: "折疊收納盒",
    style: "折疊/提把",
    note: "材質與圖片待商品詳頁確認；外徑依尺寸原文順序拆分",
    updatedAt: "2026-07-15",
  },
  {
    id: "daiso-industrial-folding-basket-gray",
    name: "工業風折疊收納籃/灰",
    brand: "DAISO",
    model: "30 x 12.3 x 20 cm",
    widthCm: 30,
    depthCm: 12.3,
    heightCm: 20,
    priceTwd: 69,
    channel: "DAISO",
    purchaseUrl: "https://shop.daiso.com.tw/pages/daiso01-14",
    imageUrl: "",
    hasLid: false,
    isTransparent: false,
    isStackable: false,
    material: "未標示",
    color: "灰",
    category: "折疊收納盒",
    style: "工業風/折疊",
    note: "材質與圖片待商品詳頁確認；外徑依尺寸原文順序拆分",
    updatedAt: "2026-07-15",
  },
  {
    id: "daiso-denim-folding-storage-box",
    name: "折疊收納箱/附隔板 牛仔風",
    brand: "DAISO",
    model: "27 x 19 x 16 cm",
    widthCm: 27,
    depthCm: 19,
    heightCm: 16,
    priceTwd: 99,
    channel: "DAISO",
    purchaseUrl: "https://shop.daiso.com.tw/pages/daiso01-14",
    imageUrl: "",
    hasLid: false,
    isTransparent: false,
    isStackable: false,
    material: "未標示",
    color: "牛仔風",
    category: "折疊收納盒",
    style: "布製/牛仔風/折疊",
    note: "材質與圖片待商品詳頁確認；外徑依尺寸原文順序拆分",
    updatedAt: "2026-07-15",
  },
  {
    id: "muji-pp-horizontal-shallow",
    name: "聚丙烯收納盒 橫式 淺型",
    brand: "MUJI無印良品",
    model: "37 x 26 x 12 cm",
    widthCm: 37,
    depthCm: 26,
    heightCm: 12,
    priceTwd: null,
    channel: "MUJI無印良品",
    purchaseUrl: "https://www.muji.com/tw/zh_tw/store/cmdty/section/S20015",
    imageUrl: "",
    hasLid: false,
    isTransparent: true,
    isStackable: true,
    material: "聚丙烯",
    color: "半透明",
    category: "聚丙烯收納",
    style: "極簡/透明/可堆疊",
    note: "台灣官方商品頁目前連線逾時；先保留為待驗證樣本，價格與圖片待人工確認；外徑依尺寸原文順序拆分",
    updatedAt: "2026-07-15",
  },
  {
    id: "muji-pp-horizontal-standard",
    name: "聚丙烯收納盒 橫式 標準型",
    brand: "MUJI無印良品",
    model: "37 x 26 x 17.5 cm",
    widthCm: 37,
    depthCm: 26,
    heightCm: 17.5,
    priceTwd: null,
    channel: "MUJI無印良品",
    purchaseUrl: "https://www.muji.com/tw/zh_tw/store/cmdty/section/S20015",
    imageUrl: "",
    hasLid: false,
    isTransparent: true,
    isStackable: true,
    material: "聚丙烯",
    color: "半透明",
    category: "聚丙烯收納",
    style: "極簡/透明/可堆疊",
    note: "台灣官方商品頁目前連線逾時；先保留為待驗證樣本，價格與圖片待人工確認；外徑依尺寸原文順序拆分",
    updatedAt: "2026-07-15",
  },
  {
    id: "muji-pp-horizontal-deep",
    name: "聚丙烯收納盒 橫式 深型",
    brand: "MUJI無印良品",
    model: "37 x 26 x 24 cm",
    widthCm: 37,
    depthCm: 26,
    heightCm: 24,
    priceTwd: null,
    channel: "MUJI無印良品",
    purchaseUrl: "https://www.muji.com/tw/zh_tw/store/cmdty/section/S20015",
    imageUrl: "",
    hasLid: false,
    isTransparent: true,
    isStackable: true,
    material: "聚丙烯",
    color: "半透明",
    category: "聚丙烯收納",
    style: "極簡/透明/可堆疊",
    note: "台灣官方商品頁目前連線逾時；先保留為待驗證樣本，價格與圖片待人工確認；外徑依尺寸原文順序拆分",
    updatedAt: "2026-07-15",
  },
  {
    id: "muji-pp-horizontal-extra-deep",
    name: "聚丙烯收納盒 橫式 深大型",
    brand: "MUJI無印良品",
    model: "37 x 26 x 32 cm",
    widthCm: 37,
    depthCm: 26,
    heightCm: 32,
    priceTwd: null,
    channel: "MUJI無印良品",
    purchaseUrl: "https://www.muji.com/tw/zh_tw/store/cmdty/section/S20015",
    imageUrl: "",
    hasLid: false,
    isTransparent: true,
    isStackable: true,
    material: "聚丙烯",
    color: "半透明",
    category: "聚丙烯收納",
    style: "極簡/透明/可堆疊",
    note: "台灣官方商品頁目前連線逾時；先保留為待驗證樣本，價格與圖片待人工確認；外徑依尺寸原文順序拆分",
    updatedAt: "2026-07-15",
  },
];
