const products = [
  {
    id: "muji-pp-case-shallow",
    name: "PP 收納盒 淺型",
    brand: "無印良品",
    model: "PP Shallow",
    widthCm: 37,
    depthCm: 26,
    heightCm: 12,
    priceTwd: 249,
    channel: "無印良品",
    purchaseUrl: "https://www.muji.com/tw/",
    imageUrl: "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=900&q=80",
    hasLid: false,
    isTransparent: true,
    isStackable: true,
    material: "PP",
    category: "抽屜盒",
    updatedAt: "2026-07-13",
  },
  {
    id: "muji-pp-case-standard",
    name: "PP 收納盒 標準型",
    brand: "無印良品",
    model: "PP Standard",
    widthCm: 37,
    depthCm: 26,
    heightCm: 17.5,
    priceTwd: 299,
    channel: "無印良品",
    purchaseUrl: "https://www.muji.com/tw/",
    imageUrl: "https://images.unsplash.com/photo-1618220048045-10a6dbdf83e0?auto=format&fit=crop&w=900&q=80",
    hasLid: false,
    isTransparent: true,
    isStackable: true,
    material: "PP",
    category: "抽屜盒",
    updatedAt: "2026-07-13",
  },
  {
    id: "ikea-samla-11l",
    name: "SAMLA 透明收納盒 11L",
    brand: "IKEA",
    model: "SAMLA 11L",
    widthCm: 39,
    depthCm: 28,
    heightCm: 14,
    priceTwd: 99,
    channel: "IKEA",
    purchaseUrl: "https://www.ikea.com.tw/",
    imageUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=900&q=80",
    hasLid: false,
    isTransparent: true,
    isStackable: true,
    material: "PP",
    category: "收納箱",
    updatedAt: "2026-07-13",
  },
  {
    id: "ikea-samla-22l",
    name: "SAMLA 透明收納盒 22L",
    brand: "IKEA",
    model: "SAMLA 22L",
    widthCm: 39,
    depthCm: 28,
    heightCm: 28,
    priceTwd: 149,
    channel: "IKEA",
    purchaseUrl: "https://www.ikea.com.tw/",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&q=80",
    hasLid: false,
    isTransparent: true,
    isStackable: true,
    material: "PP",
    category: "收納箱",
    updatedAt: "2026-07-13",
  },
  {
    id: "keyway-mini-lid-box",
    name: "聯府 KEYWAY 透明整理盒",
    brand: "KEYWAY 聯府",
    model: "Mini Box",
    widthCm: 31,
    depthCm: 22,
    heightCm: 14,
    priceTwd: 129,
    channel: "momo",
    purchaseUrl: "https://www.momoshop.com.tw/",
    imageUrl: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=900&q=80",
    hasLid: true,
    isTransparent: true,
    isStackable: true,
    material: "PP",
    category: "整理盒",
    updatedAt: "2026-07-13",
  },
  {
    id: "keyway-deep-storage-box",
    name: "聯府 KEYWAY 深型收納箱",
    brand: "KEYWAY 聯府",
    model: "Deep Box",
    widthCm: 39,
    depthCm: 50,
    heightCm: 24,
    priceTwd: 399,
    channel: "PChome",
    purchaseUrl: "https://24h.pchome.com.tw/",
    imageUrl: "https://images.unsplash.com/photo-1600607686527-6fb886090705?auto=format&fit=crop&w=900&q=80",
    hasLid: true,
    isTransparent: false,
    isStackable: true,
    material: "PP",
    category: "收納箱",
    updatedAt: "2026-07-13",
  },
  {
    id: "hola-fabric-drawer",
    name: "特力屋布面抽屜收納盒",
    brand: "特力屋",
    model: "Fabric Drawer",
    widthCm: 33,
    depthCm: 33,
    heightCm: 28,
    priceTwd: 199,
    channel: "特力屋",
    purchaseUrl: "https://www.trplus.com.tw/",
    imageUrl: "https://images.unsplash.com/photo-1602872030490-4a484a7b3ba6?auto=format&fit=crop&w=900&q=80",
    hasLid: false,
    isTransparent: false,
    isStackable: false,
    material: "不織布",
    category: "抽屜盒",
    updatedAt: "2026-07-13",
  },
  {
    id: "living-storage-wide",
    name: "生活工場寬版桌面整理盒",
    brand: "生活工場",
    model: "Desktop Wide",
    widthCm: 24,
    depthCm: 16,
    heightCm: 10,
    priceTwd: 159,
    channel: "生活工場",
    purchaseUrl: "https://www.workinghouse.com.tw/",
    imageUrl: "https://images.unsplash.com/photo-1610701596061-2ecf227e85b2?auto=format&fit=crop&w=900&q=80",
    hasLid: false,
    isTransparent: false,
    isStackable: true,
    material: "ABS",
    category: "桌面整理",
    updatedAt: "2026-07-13",
  },
  {
    id: "shopee-stack-bin",
    name: "斜口可堆疊零件收納盒",
    brand: "台灣製",
    model: "Stack Bin",
    widthCm: 18,
    depthCm: 26,
    heightCm: 13,
    priceTwd: 89,
    channel: "蝦皮商城",
    purchaseUrl: "https://shopee.tw/mall",
    imageUrl: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=900&q=80",
    hasLid: false,
    isTransparent: false,
    isStackable: true,
    material: "PP",
    category: "零件盒",
    updatedAt: "2026-07-13",
  },
  {
    id: "pchome-wheeled-box",
    name: "附輪床底收納箱",
    brand: "台灣製",
    model: "Underbed Wheel",
    widthCm: 40,
    depthCm: 58,
    heightCm: 18,
    priceTwd: 499,
    channel: "PChome",
    purchaseUrl: "https://24h.pchome.com.tw/",
    imageUrl: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=80",
    hasLid: true,
    isTransparent: true,
    isStackable: false,
    material: "PP",
    category: "床底收納",
    updatedAt: "2026-07-13",
  },
  {
    id: "momo-clear-drawer-s",
    name: "透明三層抽屜整理箱 小",
    brand: "嚴選家",
    model: "Drawer S",
    widthCm: 28,
    depthCm: 36,
    heightCm: 18,
    priceTwd: 329,
    channel: "momo",
    purchaseUrl: "https://www.momoshop.com.tw/",
    imageUrl: "https://images.unsplash.com/photo-1616486886892-ff366aa67ba4?auto=format&fit=crop&w=900&q=80",
    hasLid: false,
    isTransparent: true,
    isStackable: true,
    material: "PS",
    category: "抽屜盒",
    updatedAt: "2026-07-13",
  },
  {
    id: "trplus-closet-bin",
    name: "衣櫃分類收納盒",
    brand: "特力屋",
    model: "Closet Bin",
    widthCm: 30,
    depthCm: 40,
    heightCm: 20,
    priceTwd: 249,
    channel: "特力屋",
    purchaseUrl: "https://www.trplus.com.tw/",
    imageUrl: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=900&q=80",
    hasLid: true,
    isTransparent: false,
    isStackable: true,
    material: "PP",
    category: "衣櫃收納",
    updatedAt: "2026-07-13",
  },
];
